services:
    database:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_DATABASE: bank-app
            MONGO_INITDB_ROOT_USERNAME: tux
            MONGO_INITDB_ROOT_PASSWORD: tux123
